import { StyleSheet } from "react-native";

export
    const styles = StyleSheet.create({
        header: {
            flexDirection: "row",
            alignItems: "center",
            paddingHorizontal: 16,
            paddingTop: 32,
            paddingBottom: 8,
            borderBottomWidth: 1,
            borderBottomColor: "#fff",
        },
        backButton: {
            position: "absolute",
            left: 15,
            width: 40,
            height: 40,
            borderRadius: 20,
            borderWidth: 2,
            borderColor: "#321904",
            justifyContent: "center",
            alignItems: "center",
            top: 30,
        },
        title: {
            fontSize: 25,
            fontWeight: "bold",
            color: "#4f1a04ff",
            textAlign: "center",
        },

        card: {
            backgroundColor: "#f7eee5ff",
            borderRadius: 16,
            padding: 24,
            alignItems: "center",
            marginBottom: 20,
            shadowColor: "#000",
            shadowOpacity: 0.1,
            shadowRadius: 10,
            width: "100%",
        },
        heartContainer: {
            position: "relative",
            marginBottom: 16,
        },
        ping: {
            position: "absolute",
            width: 80,
            height: 80,
            borderRadius: 40,
            backgroundColor: "rgba(220,38,38,0.2)",
            top: 0,
            left: 0,
            zIndex: -1,
        },
        bpm: { fontSize: 64, fontWeight: "bold", color: "#C2410C" },
        bpmLabel: { fontSize: 20, color: "#EA580C", marginBottom: 12 },
        infoCard: {
            backgroundColor: "rgba(249, 245, 239, 0.6)",
            borderRadius: 12,
            padding: 16,
            width: "100%",
            marginBottom: 20,
        },
        infoTitle: {
            color: "#C2410C",
            fontSize: 20,
            fontWeight: "bold",
            marginBottom: 12,
            textAlign: "center",
        },
        infoRow: {
            flexDirection: "row",
            justifyContent: "space-between",
            marginBottom: 8,
        },
        infoLabel: { color: "#EA580C", fontSize: 20 },
        infoValue: { color: "#C2410C", fontSize: 20, fontWeight: "bold" },
        button: {
            backgroundColor: "#F97316",
            paddingVertical: 12,
            paddingHorizontal: 36,
            borderRadius: 24,
        },
        buttonText: { color: "#fff", fontSize: 20, fontWeight: "bold" },
        buttonPermissoes: {
            backgroundColor: "#ee8439ff",
            paddingVertical: 12,
            paddingHorizontal: 32,
            borderRadius: 24,
            alignItems: "center",
        },
    });
