import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: "#fff" },
    scrollContent: { padding: 20, paddingBottom: 120 },
    header: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 20,
        position: "relative",
    },
    backButton: {
        position: "absolute",
        left: 0,
        width: 40,
        height: 40,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: "#321904",
        justifyContent: "center",
        alignItems: "center",
        top: 10,
    },
    headerTitle: { fontSize: 25, fontWeight: "bold", color: "#321904", top: 10 },
    section: { marginBottom: 20 },
    sectionTitle: {
        fontSize: 20,
        fontWeight: "bold",
        color: "#321904",
        marginBottom: 10,
    },
    firstSectionTitle: {
        fontSize: 20,
        fontWeight: "bold",
        color: "#321904",
        marginBottom: 10,
        marginTop: 18,
    },
    optionRow: { flexDirection: "row", alignItems: "center", marginBottom: 8 },
    optionText: { flex: 1, marginLeft: 8, color: "#321904", fontSize: 20 },
    input: {
        backgroundColor: "#f7eee5ff",
        padding: 14,
        borderRadius: 6,
        marginBottom: 16,
        fontSize: 20,
        color: "#321904",
    },
    inputPressao: {
        backgroundColor: "#f7eee5ff",
        width: 110,
        padding: 14,
        borderRadius: 6,
        marginBottom: 16,
        fontSize: 20,
        color: "#321904",
    },
    divider: {
        borderBottomWidth: 1,
        borderBottomColor: "#ddd",
        marginVertical: 15,
    },
    remedioButton: {
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#FBB65A",
        paddingVertical: 12,
        borderRadius: 6,
        marginTop: 12,
    },
    remedioButtonText: {
        fontSize: 20,
        fontWeight: "bold",
        color: "#321904",
    },
    saveButton: {
        backgroundColor: "#F28B0C",
        paddingVertical: 14,
        borderRadius: 6,
        alignItems: "center",
        marginTop: 10,
    },
    saveButtonText: { color: "#fff", fontSize: 20, fontWeight: "bold" },
    homeButton: {
        position: "absolute",
        bottom: 20,
        alignSelf: "center",
        backgroundColor: "#fff",
        borderRadius: 30,
        padding: 14,
        elevation: 5,
        shadowColor: "#321904",
        shadowOpacity: 0.1,
        shadowRadius: 4,
        shadowOffset: { width: 0, height: 2 },
    },
    separator: {
        fontSize: 20,
        marginHorizontal: 5,
    },
    barraHorizontal: {
        height: 1,
        backgroundColor: "grey",
        width: 115,
        marginVertical: 10,
    },
});
