import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: "#fff" },
    scrollContent: { padding: 20, paddingBottom: 150 },
    header: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        position: "relative",
        marginBottom: 10,
    },
    backButton: {
        position: "absolute",
        left: 0,
        width: 40,
        height: 40,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: "#321904",
        justifyContent: "center",
        alignItems: "center",
        top: 10,
    },
    headerTitle: { fontSize: 25, fontWeight: "bold", color: "#321904", top: 10 },
    progressText: {
        textAlign: "center",
        fontSize: 18,
        color: "#7a6c5d",
        marginBottom: 15,
    },
    section: { marginBottom: 25 },
    sectionTitle: { fontSize: 20, fontWeight: "bold", color: "#321904", marginBottom: 12 },
    label: { fontSize: 20, color: "#321904", marginBottom: 6, marginTop: 10 },
    input: {
        backgroundColor: "#f7eee5ff",
        padding: 14,
        borderRadius: 6,
        marginBottom: 14,
        fontSize: 20,
        color: "#321904",
        textAlignVertical: "top",
    },
    radioOption: { flexDirection: "row", alignItems: "center", marginBottom: 10 },
    checkboxRow: { flexDirection: "row", alignItems: "center", marginBottom: 10 },
    optionText: { marginLeft: 8, fontSize: 20, color: "#321904", flexShrink: 1 },
    divider: {
        borderBottomWidth: 1,
        borderBottomColor: "#d8c9b8",
        marginVertical: 10,
    },
    saveButton: {
        backgroundColor: "#F28B0C",
        paddingVertical: 16,
        borderRadius: 8,
        alignItems: "center",
        marginTop: 20,
    },
    saveButtonText: { color: "#fff", fontSize: 20, fontWeight: "bold" },
});
